-- The portmasters. Generated by `codex ferry`; do not hand-edit.
--
-- 9 piers, 62 routes. One connector per pier: the mapdb records
-- pairs, and nine piers over nine destinations would be eighty-one.
--
-- Twenty minutes, and only if the player asked for ferries. The mapdb
-- prices these with a StringProc rather than a number --
--
--   ;e UserVars.mapdb_use_portmasters == true ? 1200 : nil
--
-- and `nil` means impassable. That is the same shape as `ice_mode`: a
-- preference, a thing the player chose. Nobody wants a router quietly
-- putting them on a twenty-minute boat to save thirty seconds of
-- walking, and nobody should find that out at sea.

INSERT INTO conditions(id, description) VALUES
  ('no-portmasters', 'the player has not opted in to ferry travel');
INSERT INTO condition_terms(condition_id, grp, seq, subject, key, op, value) VALUES
  ('no-portmasters', 0, 0, 'preference', 'use_portmasters', 'ne', 'true');
INSERT INTO condition_effects(condition_id, effect, amount) VALUES
  ('no-portmasters', 'forbid', 0);

INSERT INTO room_sets(name, description) VALUES
  ('pier:7111', 'A pier with a portmaster.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES
  ('pier:7111', 0, 'room', '7111');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('portmaster:7111', 'only', 'pier:7111', 0, 'The portmaster, to 8 places.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('portmaster:7111', 'no-portmasters');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7111', 'fixed', 4744014, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7111', 'fixed', 2101030, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7111', 'fixed', 3002033, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7111', 'fixed', 7118259, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7111', 'fixed', 7136032, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7111', 'fixed', 7133026, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7111', 'fixed', 7140125, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7111', 'fixed', 7142028, 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7111', 'fixed', 4744014, 0, 'ask portmaster about travel 2', '', 0),
  ('portmaster:7111', 'fixed', 4744014, 1, 'ask portmaster about travel 2', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7111', 'fixed', 2101030, 0, 'ask portmaster about travel 3', '', 0),
  ('portmaster:7111', 'fixed', 2101030, 1, 'ask portmaster about travel 3', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7111', 'fixed', 3002033, 0, 'ask portmaster about travel 4', '', 0),
  ('portmaster:7111', 'fixed', 3002033, 1, 'ask portmaster about travel 4', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7111', 'fixed', 7118259, 0, 'ask portmaster about travel 5', '', 0),
  ('portmaster:7111', 'fixed', 7118259, 1, 'ask portmaster about travel 5', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7111', 'fixed', 7136032, 0, 'ask portmaster about travel 6', '', 0),
  ('portmaster:7111', 'fixed', 7136032, 1, 'ask portmaster about travel 6', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7111', 'fixed', 7133026, 0, 'ask portmaster about travel 7', '', 0),
  ('portmaster:7111', 'fixed', 7133026, 1, 'ask portmaster about travel 7', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7111', 'fixed', 7140125, 0, 'ask portmaster about travel 8', '', 0),
  ('portmaster:7111', 'fixed', 7140125, 1, 'ask portmaster about travel 8', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7111', 'fixed', 7142028, 0, 'ask portmaster about travel 11', '', 0),
  ('portmaster:7111', 'fixed', 7142028, 1, 'ask portmaster about travel 11', 'A crew member escorts you off the ship.', 1200000);

INSERT INTO room_sets(name, description) VALUES
  ('pier:2101030', 'A pier with a portmaster.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES
  ('pier:2101030', 0, 'room', '2101030');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('portmaster:2101030', 'only', 'pier:2101030', 0, 'The portmaster, to 7 places.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('portmaster:2101030', 'no-portmasters');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:2101030', 'fixed', 7111, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:2101030', 'fixed', 4744014, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:2101030', 'fixed', 3002033, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:2101030', 'fixed', 7118259, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:2101030', 'fixed', 7136032, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:2101030', 'fixed', 7133026, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:2101030', 'fixed', 7140125, 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:2101030', 'fixed', 7111, 0, 'ask portmaster about travel 1', '', 0),
  ('portmaster:2101030', 'fixed', 7111, 1, 'ask portmaster about travel 1', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:2101030', 'fixed', 4744014, 0, 'ask portmaster about travel 2', '', 0),
  ('portmaster:2101030', 'fixed', 4744014, 1, 'ask portmaster about travel 2', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:2101030', 'fixed', 3002033, 0, 'ask portmaster about travel 4', '', 0),
  ('portmaster:2101030', 'fixed', 3002033, 1, 'ask portmaster about travel 4', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:2101030', 'fixed', 7118259, 0, 'ask portmaster about travel 5', '', 0),
  ('portmaster:2101030', 'fixed', 7118259, 1, 'ask portmaster about travel 5', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:2101030', 'fixed', 7136032, 0, 'ask portmaster about travel 6', '', 0),
  ('portmaster:2101030', 'fixed', 7136032, 1, 'ask portmaster about travel 6', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:2101030', 'fixed', 7133026, 0, 'ask portmaster about travel 7', '', 0),
  ('portmaster:2101030', 'fixed', 7133026, 1, 'ask portmaster about travel 7', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:2101030', 'fixed', 7140125, 0, 'ask portmaster about travel 8', '', 0),
  ('portmaster:2101030', 'fixed', 7140125, 1, 'ask portmaster about travel 8', 'A crew member escorts you off the ship.', 1200000);

INSERT INTO room_sets(name, description) VALUES
  ('pier:3002033', 'A pier with a portmaster.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES
  ('pier:3002033', 0, 'room', '3002033');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('portmaster:3002033', 'only', 'pier:3002033', 0, 'The portmaster, to 7 places.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('portmaster:3002033', 'no-portmasters');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:3002033', 'fixed', 7111, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:3002033', 'fixed', 4744014, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:3002033', 'fixed', 2101030, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:3002033', 'fixed', 7118259, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:3002033', 'fixed', 7136032, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:3002033', 'fixed', 7133026, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:3002033', 'fixed', 7140125, 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:3002033', 'fixed', 7111, 0, 'ask portmaster about travel 1', '', 0),
  ('portmaster:3002033', 'fixed', 7111, 1, 'ask portmaster about travel 1', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:3002033', 'fixed', 4744014, 0, 'ask portmaster about travel 2', '', 0),
  ('portmaster:3002033', 'fixed', 4744014, 1, 'ask portmaster about travel 2', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:3002033', 'fixed', 2101030, 0, 'ask portmaster about travel 3', '', 0),
  ('portmaster:3002033', 'fixed', 2101030, 1, 'ask portmaster about travel 3', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:3002033', 'fixed', 7118259, 0, 'ask portmaster about travel 5', '', 0),
  ('portmaster:3002033', 'fixed', 7118259, 1, 'ask portmaster about travel 5', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:3002033', 'fixed', 7136032, 0, 'ask portmaster about travel 6', '', 0),
  ('portmaster:3002033', 'fixed', 7136032, 1, 'ask portmaster about travel 6', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:3002033', 'fixed', 7133026, 0, 'ask portmaster about travel 7', '', 0),
  ('portmaster:3002033', 'fixed', 7133026, 1, 'ask portmaster about travel 7', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:3002033', 'fixed', 7140125, 0, 'ask portmaster about travel 8', '', 0),
  ('portmaster:3002033', 'fixed', 7140125, 1, 'ask portmaster about travel 8', 'A crew member escorts you off the ship.', 1200000);

INSERT INTO room_sets(name, description) VALUES
  ('pier:4744014', 'A pier with a portmaster.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES
  ('pier:4744014', 0, 'room', '4744014');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('portmaster:4744014', 'only', 'pier:4744014', 0, 'The portmaster, to 8 places.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('portmaster:4744014', 'no-portmasters');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:4744014', 'fixed', 7111, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:4744014', 'fixed', 2101030, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:4744014', 'fixed', 3002033, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:4744014', 'fixed', 7118259, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:4744014', 'fixed', 7136032, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:4744014', 'fixed', 7133026, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:4744014', 'fixed', 7140125, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:4744014', 'fixed', 7142028, 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:4744014', 'fixed', 7111, 0, 'ask portmaster about travel 1', '', 0),
  ('portmaster:4744014', 'fixed', 7111, 1, 'ask portmaster about travel 1', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:4744014', 'fixed', 2101030, 0, 'ask portmaster about travel 3', '', 0),
  ('portmaster:4744014', 'fixed', 2101030, 1, 'ask portmaster about travel 3', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:4744014', 'fixed', 3002033, 0, 'ask portmaster about travel 4', '', 0),
  ('portmaster:4744014', 'fixed', 3002033, 1, 'ask portmaster about travel 4', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:4744014', 'fixed', 7118259, 0, 'ask portmaster about travel 5', '', 0),
  ('portmaster:4744014', 'fixed', 7118259, 1, 'ask portmaster about travel 5', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:4744014', 'fixed', 7136032, 0, 'ask portmaster about travel 6', '', 0),
  ('portmaster:4744014', 'fixed', 7136032, 1, 'ask portmaster about travel 6', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:4744014', 'fixed', 7133026, 0, 'ask portmaster about travel 7', '', 0),
  ('portmaster:4744014', 'fixed', 7133026, 1, 'ask portmaster about travel 7', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:4744014', 'fixed', 7140125, 0, 'ask portmaster about travel 8', '', 0),
  ('portmaster:4744014', 'fixed', 7140125, 1, 'ask portmaster about travel 8', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:4744014', 'fixed', 7142028, 0, 'ask portmaster about travel 11', '', 0),
  ('portmaster:4744014', 'fixed', 7142028, 1, 'ask portmaster about travel 11', 'A crew member escorts you off the ship.', 1200000);

INSERT INTO room_sets(name, description) VALUES
  ('pier:7118259', 'A pier with a portmaster.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES
  ('pier:7118259', 0, 'room', '7118259');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('portmaster:7118259', 'only', 'pier:7118259', 0, 'The portmaster, to 7 places.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('portmaster:7118259', 'no-portmasters');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7118259', 'fixed', 7111, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7118259', 'fixed', 4744014, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7118259', 'fixed', 2101030, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7118259', 'fixed', 3002033, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7118259', 'fixed', 7136032, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7118259', 'fixed', 7133026, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7118259', 'fixed', 7140125, 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7118259', 'fixed', 7111, 0, 'ask portmaster about travel 1', '', 0),
  ('portmaster:7118259', 'fixed', 7111, 1, 'ask portmaster about travel 1', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7118259', 'fixed', 4744014, 0, 'ask portmaster about travel 2', '', 0),
  ('portmaster:7118259', 'fixed', 4744014, 1, 'ask portmaster about travel 2', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7118259', 'fixed', 2101030, 0, 'ask portmaster about travel 3', '', 0),
  ('portmaster:7118259', 'fixed', 2101030, 1, 'ask portmaster about travel 3', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7118259', 'fixed', 3002033, 0, 'ask portmaster about travel 4', '', 0),
  ('portmaster:7118259', 'fixed', 3002033, 1, 'ask portmaster about travel 4', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7118259', 'fixed', 7136032, 0, 'ask portmaster about travel 6', '', 0),
  ('portmaster:7118259', 'fixed', 7136032, 1, 'ask portmaster about travel 6', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7118259', 'fixed', 7133026, 0, 'ask portmaster about travel 7', '', 0),
  ('portmaster:7118259', 'fixed', 7133026, 1, 'ask portmaster about travel 7', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7118259', 'fixed', 7140125, 0, 'ask portmaster about travel 8', '', 0),
  ('portmaster:7118259', 'fixed', 7140125, 1, 'ask portmaster about travel 8', 'A crew member escorts you off the ship.', 1200000);

INSERT INTO room_sets(name, description) VALUES
  ('pier:7133026', 'A pier with a portmaster.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES
  ('pier:7133026', 0, 'room', '7133026');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('portmaster:7133026', 'only', 'pier:7133026', 0, 'The portmaster, to 8 places.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('portmaster:7133026', 'no-portmasters');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7133026', 'fixed', 7111, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7133026', 'fixed', 4744014, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7133026', 'fixed', 2101030, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7133026', 'fixed', 3002033, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7133026', 'fixed', 7118259, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7133026', 'fixed', 7136032, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7133026', 'fixed', 7140125, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7133026', 'fixed', 7142028, 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7133026', 'fixed', 7111, 0, 'ask portmaster about travel 1', '', 0),
  ('portmaster:7133026', 'fixed', 7111, 1, 'ask portmaster about travel 1', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7133026', 'fixed', 4744014, 0, 'ask portmaster about travel 2', '', 0),
  ('portmaster:7133026', 'fixed', 4744014, 1, 'ask portmaster about travel 2', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7133026', 'fixed', 2101030, 0, 'ask portmaster about travel 3', '', 0),
  ('portmaster:7133026', 'fixed', 2101030, 1, 'ask portmaster about travel 3', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7133026', 'fixed', 3002033, 0, 'ask portmaster about travel 4', '', 0),
  ('portmaster:7133026', 'fixed', 3002033, 1, 'ask portmaster about travel 4', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7133026', 'fixed', 7118259, 0, 'ask portmaster about travel 5', '', 0),
  ('portmaster:7133026', 'fixed', 7118259, 1, 'ask portmaster about travel 5', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7133026', 'fixed', 7136032, 0, 'ask portmaster about travel 6', '', 0),
  ('portmaster:7133026', 'fixed', 7136032, 1, 'ask portmaster about travel 6', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7133026', 'fixed', 7140125, 0, 'ask portmaster about travel 8', '', 0),
  ('portmaster:7133026', 'fixed', 7140125, 1, 'ask portmaster about travel 8', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7133026', 'fixed', 7142028, 0, 'ask portmaster about travel 11', '', 0),
  ('portmaster:7133026', 'fixed', 7142028, 1, 'ask portmaster about travel 11', 'A crew member escorts you off the ship.', 1200000);

INSERT INTO room_sets(name, description) VALUES
  ('pier:7136032', 'A pier with a portmaster.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES
  ('pier:7136032', 0, 'room', '7136032');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('portmaster:7136032', 'only', 'pier:7136032', 0, 'The portmaster, to 7 places.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('portmaster:7136032', 'no-portmasters');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7136032', 'fixed', 7111, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7136032', 'fixed', 4744014, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7136032', 'fixed', 2101030, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7136032', 'fixed', 3002033, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7136032', 'fixed', 7118259, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7136032', 'fixed', 7133026, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7136032', 'fixed', 7140125, 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7136032', 'fixed', 7111, 0, 'ask portmaster about travel 1', '', 0),
  ('portmaster:7136032', 'fixed', 7111, 1, 'ask portmaster about travel 1', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7136032', 'fixed', 4744014, 0, 'ask portmaster about travel 2', '', 0),
  ('portmaster:7136032', 'fixed', 4744014, 1, 'ask portmaster about travel 2', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7136032', 'fixed', 2101030, 0, 'ask portmaster about travel 3', '', 0),
  ('portmaster:7136032', 'fixed', 2101030, 1, 'ask portmaster about travel 3', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7136032', 'fixed', 3002033, 0, 'ask portmaster about travel 4', '', 0),
  ('portmaster:7136032', 'fixed', 3002033, 1, 'ask portmaster about travel 4', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7136032', 'fixed', 7118259, 0, 'ask portmaster about travel 5', '', 0),
  ('portmaster:7136032', 'fixed', 7118259, 1, 'ask portmaster about travel 5', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7136032', 'fixed', 7133026, 0, 'ask portmaster about travel 7', '', 0),
  ('portmaster:7136032', 'fixed', 7133026, 1, 'ask portmaster about travel 7', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7136032', 'fixed', 7140125, 0, 'ask portmaster about travel 8', '', 0),
  ('portmaster:7136032', 'fixed', 7140125, 1, 'ask portmaster about travel 8', 'A crew member escorts you off the ship.', 1200000);

INSERT INTO room_sets(name, description) VALUES
  ('pier:7140125', 'A pier with a portmaster.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES
  ('pier:7140125', 0, 'room', '7140125');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('portmaster:7140125', 'only', 'pier:7140125', 0, 'The portmaster, to 7 places.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('portmaster:7140125', 'no-portmasters');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7140125', 'fixed', 7111, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7140125', 'fixed', 4744014, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7140125', 'fixed', 2101030, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7140125', 'fixed', 3002033, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7140125', 'fixed', 7118259, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7140125', 'fixed', 7136032, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7140125', 'fixed', 7133026, 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7140125', 'fixed', 7111, 0, 'ask portmaster about travel 1', '', 0),
  ('portmaster:7140125', 'fixed', 7111, 1, 'ask portmaster about travel 1', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7140125', 'fixed', 4744014, 0, 'ask portmaster about travel 2', '', 0),
  ('portmaster:7140125', 'fixed', 4744014, 1, 'ask portmaster about travel 2', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7140125', 'fixed', 2101030, 0, 'ask portmaster about travel 3', '', 0),
  ('portmaster:7140125', 'fixed', 2101030, 1, 'ask portmaster about travel 3', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7140125', 'fixed', 3002033, 0, 'ask portmaster about travel 4', '', 0),
  ('portmaster:7140125', 'fixed', 3002033, 1, 'ask portmaster about travel 4', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7140125', 'fixed', 7118259, 0, 'ask portmaster about travel 5', '', 0),
  ('portmaster:7140125', 'fixed', 7118259, 1, 'ask portmaster about travel 5', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7140125', 'fixed', 7136032, 0, 'ask portmaster about travel 6', '', 0),
  ('portmaster:7140125', 'fixed', 7136032, 1, 'ask portmaster about travel 6', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7140125', 'fixed', 7133026, 0, 'ask portmaster about travel 7', '', 0),
  ('portmaster:7140125', 'fixed', 7133026, 1, 'ask portmaster about travel 7', 'A crew member escorts you off the ship.', 1200000);

INSERT INTO room_sets(name, description) VALUES
  ('pier:7142028', 'A pier with a portmaster.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES
  ('pier:7142028', 0, 'room', '7142028');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('portmaster:7142028', 'only', 'pier:7142028', 0, 'The portmaster, to 3 places.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('portmaster:7142028', 'no-portmasters');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7142028', 'fixed', 7111, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7142028', 'fixed', 4744014, 1200000);
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES ('portmaster:7142028', 'fixed', 7133026, 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7142028', 'fixed', 7111, 0, 'ask portmaster about travel 1', '', 0),
  ('portmaster:7142028', 'fixed', 7111, 1, 'ask portmaster about travel 1', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7142028', 'fixed', 4744014, 0, 'ask portmaster about travel 2', '', 0),
  ('portmaster:7142028', 'fixed', 4744014, 1, 'ask portmaster about travel 2', 'A crew member escorts you off the ship.', 1200000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms) VALUES
  ('portmaster:7142028', 'fixed', 7133026, 0, 'ask portmaster about travel 7', '', 0),
  ('portmaster:7142028', 'fixed', 7133026, 1, 'ask portmaster about travel 7', 'A crew member escorts you off the ship.', 1200000);

