-- The Isle of Four Winds. Generated by `codex fwi`; do not hand-edit.
--
-- A trinket you turn. 14 town squares reach Gardenia Commons with it,
-- and turning it on the island takes you back to the room you left --
-- the map database keeps that in `mapdb_fwi_return_room`, which is what
-- a destination of kind `origin` is for.
--
-- Every one of those roads is a `;e` script edge, so the extractor
-- dropped all of them and the island had no published way in at all.
--
-- The gate is the cost function, as usual:
--
--   ;e (!UserVars.mapdb_fwi_trinket.nil? and
--       !UserVars.mapdb_fwi_trinket.empty?) ? 15.0 : nil
--
-- Fifteen seconds if you have one, impassable if you do not.

-- Two gates. The trinket has no fixed name -- players own different
-- ones -- so it is named by a setting rather than written down here,
-- and a character who has not named theirs is not offered the road.
INSERT INTO conditions(id, description) VALUES
  ('no-fwi-trinket', 'the character has not named their Four Winds trinket'),
  ('not-premium', 'the account is not a Premium subscription');
INSERT INTO condition_terms(condition_id, grp, seq, subject, key, op, value) VALUES
  ('no-fwi-trinket', 0, 0, 'preference', 'fwi_trinket', 'absent', ''),
  ('not-premium', 0, 0, 'stat', 'subscription', 'ne', 'Premium');
INSERT INTO condition_effects(condition_id, effect, amount) VALUES
  ('no-fwi-trinket', 'forbid', 0),
  ('not-premium', 'forbid', 0);

INSERT INTO room_sets(name, description) VALUES
  ('fwi-anchors', 'Town squares the Four Winds trinket works from.');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 0, 'room', '7046');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 1, 'room', '2101006');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 2, 'room', '3001031');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 3, 'room', '4042301');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 4, 'room', '4209023');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 5, 'room', '7118213');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 6, 'room', '7140012');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 7, 'room', '7150607');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 8, 'room', '7503202');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 9, 'room', '13006019');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 10, 'room', '13101017');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 11, 'room', '14050006');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 12, 'room', '14100043');
INSERT INTO room_set_terms(set_name, seq, op, value) VALUES ('fwi-anchors', 13, 'room', '14150102');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('fwi:trinket:out', 'only', 'fwi-anchors', 0,
   'Turn the Four Winds trinket, from a town square to the island.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('fwi:trinket:out', 'no-fwi-trinket'),
  ('fwi:trinket:out', 'not-premium');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES
  ('fwi:trinket:out', 'fixed', 3201029, 15000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms)
  VALUES ('fwi:trinket:out', 'fixed', 3201029, 0,
    'turn my #{setting:travel/fwi_trinket}', 'You get the feeling', 15000);

-- The way back. `origin` rather than a room, because the trinket
-- returns you to where you came from and no row can name that in
-- advance -- which is exactly the kind the schema has for it.
--
-- The island is named by its `location` facets rather than by listing
-- thirteen hundred uids. The private homes file under their own names
-- ("Arborsong, inside the island town of Mist Harbor") and the
-- trinket works there too.
INSERT INTO room_sets(name, description) VALUES
  ('fwi-island', 'Everywhere the Four Winds trinket takes you home from.');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 0, 'facet', 'location', 'Arborsong, inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 1, 'facet', 'location', 'Coral Villa, outside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 2, 'facet', 'location', 'Dragonfly Den, inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 3, 'facet', 'location', 'Drunken D''Wharf, inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 4, 'facet', 'location', 'Emberstone Hall (Forge), inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 5, 'facet', 'location', 'Emberstone Hall, inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 6, 'facet', 'location', 'Harbor Hideaway, inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 7, 'facet', 'location', 'Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 8, 'facet', 'location', 'Onyx Rose Ranch, inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 9, 'facet', 'location', 'Silken Mist on Four Winds Isle');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 10, 'facet', 'location', 'Stone Manor, outside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 11, 'facet', 'location', 'Sunlit Sanctuary, inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 12, 'facet', 'location', 'The Brewery, inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 13, 'facet', 'location', 'The Retreat, inside the island town of Mist Harbor');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 14, 'facet', 'location', 'the Isle of Four Winds');
INSERT INTO room_set_terms(set_name, seq, op, key, value) VALUES ('fwi-island', 15, 'facet', 'location', 'the Misted Cottage, inside the island town of Mist Harbor');
INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES
  ('fwi:trinket:home', 'only', 'fwi-island', 0,
   'Turn the Four Winds trinket again, back to where you left.');
INSERT INTO connector_conditions(connector_id, condition_id) VALUES
  ('fwi:trinket:home', 'no-fwi-trinket'),
  ('fwi:trinket:home', 'not-premium');
INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) VALUES
  ('fwi:trinket:home', 'origin', 0, 15000);
INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, timeout_ms)
  VALUES ('fwi:trinket:home', 'origin', 0, 0,
    'turn my #{setting:travel/fwi_trinket}', 'You get the feeling', 15000);
