//! Symbol of Seeking, as connectors.
//!
//! A Voln symbol that moves you from an outpost to an undead hunting ground.
//! Rank 26, spell 9826, per Lich's own society table — grounded, because a
//! condition invented here would gate a road on something untrue.
//!
//! # Why it matters more than it looks
//!
//! It is the way into the Rift. Traced: the Cavern of Ages sits in a pocket of
//! seven rooms with no reachable ancestor, and of that pocket's three doors two
//! are themselves unreachable. The third is Seeking, from Icemule Trace and the
//! Pinefar Trading Post. So the sphere is the second half of a journey whose
//! first half is this.
//!
//! # Why eight connectors and not one
//!
//! The mapdb records **37 pairs** across 8 outposts and 31 destinations. One
//! connector with eight origins and thirty-one destinations would claim 248,
//! and the 211 it invented would be roads that strand somebody. So each outpost
//! gets its own connector carrying only the destinations recorded for it.
//!
//! That the recorded set may itself be incomplete is fine and is the safe
//! direction to be wrong in: a missing road fails to route, an invented one
//! does not.
//!
//! # What it costs
//!
//! The mapdb says 0.2 seconds. That is the cost of *one* invocation, and the
//! mechanism does not take a destination — it offers you one, and you ask again
//! until it offers the one you want. Lich asks up to twenty times, each with a
//! six-second timeout. A router that believes 0.2s picks Seeking over walking
//! across the street.
//!
//! 20s is written instead: twenty asks at roughly a second of round trip each,
//! which is the honest order of magnitude rather than a measurement. It should
//! be measured on a live character and corrected.

use std::collections::BTreeMap;

/// The recorded pairs, grouped by outpost: `origin uid -> destination uids`.
pub fn pairs(json: &str) -> Result<BTreeMap<i64, Vec<i64>>, Box<dyn std::error::Error>> {
    let rooms: Vec<serde_json::Value> = serde_json::from_str(json)?;

    let mut uid_of: BTreeMap<i64, i64> = BTreeMap::new();
    for r in &rooms {
        let (Some(id), Some(uid)) = (
            r.get("id").and_then(serde_json::Value::as_i64),
            r.get("uid")
                .and_then(serde_json::Value::as_array)
                .and_then(|a| a.first())
                .and_then(serde_json::Value::as_i64),
        ) else {
            continue;
        };
        uid_of.insert(id, uid);
    }

    let mut out: BTreeMap<i64, Vec<i64>> = BTreeMap::new();
    for r in &rooms {
        let Some(from) = r
            .get("id")
            .and_then(serde_json::Value::as_i64)
            .and_then(|i| uid_of.get(&i).copied())
        else {
            continue;
        };
        let Some(wayto) = r.get("wayto").and_then(serde_json::Value::as_object) else {
            continue;
        };
        for (target, command) in wayto {
            let Some(command) = command.as_str() else {
                continue;
            };
            // The global is the mechanism: Lich stashes the destination and
            // calls one shared implementation in the Graveyard courtyard.
            if !command.contains("mapdb_seeking_destination") {
                continue;
            }
            let Some(to) = target
                .parse::<i64>()
                .ok()
                .and_then(|i| uid_of.get(&i).copied())
            else {
                continue;
            };
            let dests = out.entry(from).or_default();
            if !dests.contains(&to) {
                dests.push(to);
            }
        }
    }
    for dests in out.values_mut() {
        dests.sort_unstable();
    }
    Ok(out)
}

/// The overlay that publishes them.
pub fn to_sql(pairs: &BTreeMap<i64, Vec<i64>>) -> String {
    let total: usize = pairs.values().map(Vec::len).sum();
    let distinct: std::collections::BTreeSet<i64> = pairs.values().flatten().copied().collect();
    let mut s = String::new();
    s.push_str(&format!(
        "-- Symbol of Seeking. Generated by `codex seeking`; do not hand-edit.\n\
         --\n\
         -- {} outposts, {total} recorded destinations. One connector per\n\
         -- outpost, because the mapdb records specific pairs and not a product:\n\
         -- one connector over all of them would claim {} and invent the\n\
         -- difference, and an invented road strands somebody.\n\
         --\n\
         -- Voln rank 26, spell 9826, per Lich's society table.\n\
         --\n\
         -- The cost is 20s and it is an estimate, not a measurement. The mapdb\n\
         -- says 0.2s, which is one invocation of a mechanism that does not take\n\
         -- a destination -- it offers one, and you ask again until it offers\n\
         -- yours. Lich asks up to twenty times. A router that believes 0.2s\n\
         -- picks this over walking across the street.\n\n",
        pairs.len(),
        pairs.len() * distinct.len(),
    ));

    s.push_str(
        "INSERT INTO conditions(id, description) VALUES\n  \
         ('voln-seeking', 'a member of the Order of Voln at rank 26 or better');\n\
         INSERT INTO condition_terms(condition_id, grp, seq, subject, key, op, value) VALUES\n  \
         ('voln-seeking', 0, 0, 'society', '', 'ne', 'Order of Voln'),\n  \
         ('voln-seeking', 1, 0, 'society_rank', '', 'lt', '26');\n\
         INSERT INTO condition_effects(condition_id, effect, amount) VALUES\n  \
         ('voln-seeking', 'forbid', 0);\n\n",
    );

    for (origin, dests) in pairs {
        let id = format!("voln:seeking:{origin}");
        s.push_str(&format!(
            "INSERT INTO room_sets(name, description) VALUES\n  \
             ('voln-outpost:{origin}', 'A Voln outpost Symbol of Seeking works from.');\n\
             INSERT INTO room_set_terms(set_name, seq, op, value) VALUES\n  \
             ('voln-outpost:{origin}', 0, 'room', '{origin}');\n\
             INSERT INTO connectors(id, origin_mode, origin_set, overhead_ms, description) VALUES\n  \
             ('{id}', 'only', 'voln-outpost:{origin}', 0,\n   \
             'Symbol of Seeking, from one Voln outpost to {} recorded destinations.');\n",
            dests.len()
        ));
        for to in dests {
            s.push_str(&format!(
                "INSERT INTO connector_destinations(connector_id, kind, to_uid, cost_ms) \
                 VALUES ('{id}', 'fixed', {to}, 20000);\n"
            ));
        }
        for to in dests {
            // Ask, and keep asking: the mechanism offers a destination rather
            // than taking one. `capture` is Lich's own pattern for the room
            // name it prints; a client that parses rooms structurally should
            // compare its own room name against this destination's title
            // instead, which is why the title is published.
            s.push_str(&format!(
                "INSERT INTO connector_steps(connector_id, kind, to_uid, seq, command, expect, \
                 timeout_ms, action, capture, attempts) VALUES\n  \
                 ('{id}', 'fixed', {to}, 0, 'symbol of seeking', '', 6000, 'cycle', \
                 '<style id=\"roomName\" />(.*?)$', 20),\n  \
                 ('{id}', 'fixed', {to}, 1, 'symbol of seeking confirm', \
                 'Your surroundings blur into a white fog', 6000, 'send', '', 0);\n"
            ));
        }
        s.push('\n');
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"[
      {"id":1,"uid":[100],"wayto":{
        "2":";e $mapdb_seeking_destination = 2;Map[3600].wayto['3600'].call;",
        "3":";e $mapdb_seeking_destination = 3;Map[3600].wayto['3600'].call;",
        "4":"north"}},
      {"id":2,"uid":[200],"wayto":{}},
      {"id":3,"uid":[300],"wayto":{}},
      {"id":4,"uid":[400],"wayto":{}}
    ]"#;

    #[test]
    fn only_the_seeking_edges_are_taken() {
        let found = pairs(SAMPLE).expect("parse");
        assert_eq!(found.len(), 1, "one outpost");
        assert_eq!(found[&100], vec![200, 300], "and not the plain `north`");
    }

    /// The reason there is a connector per outpost. Two outposts with two
    /// destinations each is four roads, never eight.
    #[test]
    fn each_outpost_carries_only_its_own_destinations() {
        let sql = to_sql(&pairs(SAMPLE).expect("parse"));
        assert!(sql.contains("'voln:seeking:100', 'fixed', 200"));
        assert!(sql.contains("'voln:seeking:100', 'fixed', 300"));
        assert_eq!(
            sql.matches("INSERT INTO connectors").count(),
            1,
            "one connector per outpost"
        );
    }

    /// A cost the router can believe. 0.2s is what the mapdb says and it is
    /// the cost of asking once.
    #[test]
    fn the_cost_is_the_asking_not_one_ask() {
        let sql = to_sql(&pairs(SAMPLE).expect("parse"));
        assert!(sql.contains("20000"), "twenty asks, not one");
        assert!(!sql.contains(", 200);"), "not the mapdb's 0.2s");
    }

    /// Voln rank 26 or it is not a road at all.
    #[test]
    fn seeking_is_gated_on_the_society_and_the_rank() {
        let sql = to_sql(&pairs(SAMPLE).expect("parse"));
        assert!(sql.contains("'society', '', 'ne', 'Order of Voln'"));
        assert!(sql.contains("'society_rank', '', 'lt', '26'"));
        assert!(sql.contains("'voln-seeking', 'forbid'"));
    }
}
